Create database CustomerDetailDB

select * from customer_data

SELECT COUNT(*) FROM dbo.customer_data;

--Q1) What is Total Revenue generated by Male VS Female Customer
Select gender,sum(purchase_amount) as Revenue
from customer_data
group by gender

--Q2) Which customer used a discount but still spent more than average customer amount? 
Select customer_id, purchase_amount
from customer_data
where discount_applied = 'Yes' and purchase_amount >=(select AVG(purchase_amount) from customer_data)

--Q3) Which are top 5 products with highest average review rating?
select  top 5 item_purchased,round(avg(review_rating),2) as Average_product_rating from customer_data
group by item_purchased
order by AVG(review_rating) desc

--Q4) compare the average purchase amounts between standard and express shipping
select shipping_type,Avg(purchase_amount) as Average_Purchase_amount from customer_data
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5) Do subscribed customer spent more? compare average spent and total revenue between subscriber and non subscriber.
select subscription_status,
COUNT(customer_id) as total_customers,
AVG(purchase_amount) as avg_spent, 
SUM(Purchase_amount) as total_revenue
from customer_data
group by subscription_status

--Q6) Which 5 product have highest percentage of purchases with discount applied?
select top 5 item_purchased,100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) as discount_rate from customer_data
group by item_purchased
order by discount_rate desc

--Q7) Segment customer into new,Returning and loyal based on their total number of previous purchase, and show count of each segment.

with customer_type as (
select customer_id,previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'loyal'
	end as customer_segment
from customer_data
)

select customer_segment,count(*) as "Number of customer" from customer_type
group by customer_segment
order by count(*) desc

--Q8) What are the top 3 most purchased products within each category

with item_count as( 
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_data
group by category,item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_count
where item_rank<=3

--Q9) Are customer who are repeat buyers (more than 5 pervious purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers from customer_data
where previous_purchases > 5
group by subscription_status

--Q10) What is revenue contribution of each group
select age_group, sum(purchase_amount) as total_revenue from customer_data
group by age_group
order by total_revenue desc